apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: prometheus-system
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      # If not allowed, return blank page
       if ($remote_addr  !~ "^63\.34\.112\.27$|^85\.145\.141\.250$|^217\.120\.32\.76$|^86\.90\.167\.198$|^10\.4\.0\..*") {
          return 444;
        }
